table dim_sede
	lineageTag: 3a2346ae-f3e9-4617-8720-33d0c4ecd50b

	column id_sede
		dataType: int64
		formatString: 0
		lineageTag: 38abbbb5-2cff-4b06-b473-35cc8391626e
		summarizeBy: none
		sourceColumn: id_sede

		annotation SummarizationSetBy = Automatic

	column nombre_sede
		dataType: string
		lineageTag: 7360bdd6-d04e-4d83-8ced-1fa99d9d381e
		summarizeBy: none
		sourceColumn: nombre_sede

		annotation SummarizationSetBy = Automatic

	column ubicacion_sede
		dataType: string
		lineageTag: b0eba454-0375-44bb-a44e-45b302640676
		summarizeBy: none
		sourceColumn: ubicacion_sede

		annotation SummarizationSetBy = Automatic

	partition dim_sede = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\carlo\Descargas\VentasVehiculos.xlsx"), null, true),
				    dim_sede_Table = Origen{[Item="dim_sede",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(dim_sede_Table,{{"id_sede", Int64.Type}, {"nombre_sede", type text}, {"ubicacion_sede", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

