table Fotos_Vehiculos
	lineageTag: ba62d287-2afa-4ea5-a867-6a3e9b2ea320

	column Id
		dataType: int64
		formatString: 0
		lineageTag: b458fa8c-fbde-4be8-91e6-959f1d6a5a2f
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column Modelo
		dataType: string
		lineageTag: 142dadd9-4dbe-4c92-9fb9-f21c66404183
		summarizeBy: none
		sourceColumn: Modelo

		annotation SummarizationSetBy = Automatic

	column Version
		dataType: string
		lineageTag: 4991316b-540c-40e3-93e9-54921b9d0029
		summarizeBy: none
		sourceColumn: Version

		annotation SummarizationSetBy = Automatic

	column Precio
		dataType: int64
		formatString: 0
		lineageTag: e5db4a42-aaff-4d96-bda2-94e3286ed2b8
		summarizeBy: sum
		sourceColumn: Precio

		annotation SummarizationSetBy = Automatic

	column Imagen
		dataType: string
		lineageTag: 6818f5f3-add3-403c-bd58-fed2fc6abd15
		summarizeBy: none
		sourceColumn: Imagen

		annotation SummarizationSetBy = Automatic

	partition Fotos_Vehiculos = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\carlo\Descargas\VentasVehiculos.xlsx"), null, true),
				    Fotos_Vehiculos_Table = Origen{[Item="Fotos_Vehiculos",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(Fotos_Vehiculos_Table,{{"Id", Int64.Type}, {"Modelo", type text}, {"Version", type text}, {"Precio", Int64.Type}, {"Imagen", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

